################################################################################################################################################
# Fortify lets you build secure software fast with an appsec platform that automates testing throughout the DevSecOps pipeline. Fortify static,#
# dynamic, interactive, and runtime security testing is available on premises or as a service. To learn more about Fortify, start a free trial #
# or contact our sales team, visit microfocus.com/appsecurity.                                                                                 #
#                                                                                                                                              #
# Use this workflow template as a basis for integrating Fortify on Demand Static Application Security Testing(SAST) into your GitHub workflows.#
# This template demonstrates the steps to prepare the code+dependencies, initiate a scan, download results once complete and import into       #
# GitHub Security Code Scanning Alerts. Existing customers should review inputs and environment variables below to configure scanning against  #
# an existing application in your Fortify on Demand tenant. Additional information is available in the comments throughout the workflow, the   #
# documentation for the Fortify actions used, and the Fortify on Demand / ScanCentral Client product documentation. If you need additional     #
# assistance with configuration, feel free to create a help ticket in the Fortify on Demand portal.                                            #
################################################################################################################################################

name: Fortify AST Scan

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    
jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Run Fortify on Demand SAST & SCA Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
          debricked-sca-scan: false
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          FOD_LOGIN_EXTRA_OPTS: --socket-timeout=60s
          FOD_RELEASE: Demo Releases:fcli Test
          DO_SETUP: true
          SETUP_ACTION: https://scm.my.org/shared-repos/fcli-actions/setup.yaml
          SETUP_EXTRA_OPTS: --copy-from "${{ github.repository }}:${{ github.event.repository.default_branch }}"
          SC_CLIENT_VERSION: 24.2
          DO_PACKAGE_DEBUG: true
          #PACKAGE_EXTRA_OPTS:  -bt none
          FOD_SAST_SCAN_EXTRA_OPTS: none
          DO_WAIT: true
          DO_POLICY_CHECK: true
          POLICY_CHECK_ACTION: https://scm.my.org/shared-repos/fcli-actions/check-policy.yaml
          POLICY_CHECK_EXTRA_OPTS: --on-unsigned=ignore
          DO_JOB_SUMMARY: true
          JOB_SUMMARY_ACTION: https://scm.my.org/shared-repos/fcli-actions/job-summary.yaml
          JOB_SUMMARY_EXTRA_OPTS: --on-unsigned=ignore
          DO_PR_COMMENT: true
          PR_COMMENT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-pr-comment.yaml
          PR_COMMENT_EXTRA_OPTS: --on-unsigned=ignore
          DO_EXPORT: true
          EXPORT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-sast-report.yaml
          EXPORT_EXTRA_OPTS: --on-unsigned=ignore
          #TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
