- name: Fortify AST Scan
  uses: fortify/github-action@v1.0.0

# TODO: Customize trigger events based on your DevSecOps processes and typical FoD SAST scan time
  on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 6 * * *'

  steps:
    - name: Check Out Source Code
      uses: actions/checkout@v4
    - name: Run FoD SAST Scan
      uses: fortify/github-action/fod-sast-scan@v1
          env:
           FOD_URL: "https://ams.fortify.com/"
           FOD_API_URL: "https://api.ams.fortify.com/"
           FOD_TENANT: ${{ secrets.FOD_TENANT }}
           FOD_USER: ${{ secrets.FOD_USER }}
           FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
           FOD_RELEASE: ${{ secrets.FOD_RELEASE }}
           DO_WAIT: true
           DO_EXPORT: true
